name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SFTP upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          port: 22
          server: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          local-dir: ./backend/
          server-dir: ${{secrets.SERVER_DIR}}
          dangerous-clean-slate: true
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
      - name: Build
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          script: |
            ${{secrets.BUILD_CD}}
            ${{secrets.BUILD_SETUP}}
            composer install --optimize-autoloader --no-dev
            npm run build
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
